{
 "title": "Jenkins Job Monitoring",
 "description": "Grafana Dashboard for monitoring Jenkins Job",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "query": "label_values(jenkins_job_monitor_total_count, group)"
   },
   {
    "name": "repository",
    "query": "label_values(jenkins_job_monitor_total_count, repository)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of builds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jenkins_job_monitor_pending_count{group=\"$group\", repository=~\"$repository\"}[1h]))",
     "legendFormat": " Pending builds"
    },
    {
     "expr": "sum(increase(jenkins_job_monitor_total_count{group=\"$group\", repository=~\"$repository\"}[1h]))",
     "legendFormat": " Total builds"
    }
   ]
  },
  {
   "title": "Failure rate (hourly)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(jenkins_job_monitor_fail_count{group=\"$group\",repository=~\"$repository\"}[1h]))/sum(sum_over_time(jenkins_job_monitor_total_count{group=\"$group\",repository=~\"$repository\"}[1h])) * 100",
     "legendFormat": "Failure rate"
    }
   ]
  },
  {
   "title": "Recent average total runtime (hourly)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(jenkins_job_monitor_total_duration_seconds_sum{group=\"$group\",repository=~\"$repository\"}[1h]))/sum(sum_over_time(jenkins_job_monitor_total_count{group=\"$group\",repository=~\"$repository\"}[1h])) + sum(sum_over_time(jenkins_job_monitor_pending_count{group=\"$group\",repository=~\"$repository\"}[1h]))",
     "legendFormat": "Average duration"
    }
   ]
  },
  {
   "title": "Stage-wise average duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(jenkins_job_monitor_stage_duration{group=\"$group\",repository=~\"$repository\"}) by (stagename)",
     "legendFormat": " {{stagename}}"
    }
   ]
  },
  {
   "title": "Stage-wise failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(jenkins_job_monitor_stage_fail_count{group=\"$group\",repository=~\"$repository\"}[1h])) by (stagename)",
     "legendFormat": " {{stagename}}",
     "region": "default",
     "statistics": [ "Average" ]
    },
    { "legendFormat": "Total failures" }
   ]
  },
  {
   "title": "Build statuses",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(sum_over_time(jenkins_job_monitor_stage_fail_count{group=\"$group\",repository=~\"$repository\"}[30m])) by (jobname)"
    }
   ]
  }
 ]
}